asynchronous apex features
Aggnieszkka/SalesforceInnovativeCars pull request #2
Opened 2021-06-15 12:02 UTC by Aggnieszkka

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/CarToShowroomHandler1.cls
>              }
Why 1 at the end of the class name?

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/NewOffersEmailSender.cls
> +        String[] toAddresses = new String[] {Constants.NEW_OFFERS_EMAIL_ADDRESS};
why email from constants?

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetries.cls
> +        List<Telemetry__c> tel = [SELECT Id FROM Telemetry__c WHERE DAY_ONLY(CreatedDate) <= :d];
this line was only for the purpose of tests I guess?

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetriesTest.cls
> +    *
why this empty line? please also add proper date

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetriesTest.cls
> +        	Id batchId = Database.executeBatch(deleteOld);
formatting

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetriesTest.cls
> +* @description test class for DeleteOldTelemetries class
there should be separate class testing batch and separate one testing scheduler

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/Constants.cls
> +    public static final String CASE_ORIGIN = 'Web';
the name is not meaningfull. the same as case subject. please consider something like CASE_ORIGIN_WEB (similarly with case subject)

2021-06-16 08:36 UTC, sylwiachr commented on InnovativeCars/force-app/main/default/classes/RenovationTeamRequestSender.cls
> +        req.setEndpoint(Constants.RENOVATION_ENDPOINT);
consider having endpoint in named credentials / custom metadata / custom setting

2021-06-16 12:14 UTC, AdrianDlu requested changes

2021-06-16 12:14 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetries.cls
> +        date d = system.today().adddays(-90);
bad variable name d

2021-06-16 12:14 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/DeleteOldTelemetries.cls
> +        System.debug(Constants.TELEMETRIES_DELETED_MESSAGE);
Deubugi z logging levelem

2021-06-16 12:14 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/RenovationTeamRequestSender.cls
> +            req.setBody(JSON.serialize(newCases));
Do systemu remontowego mialy byc wyslane casy z Id

2021-06-16 12:14 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/TestFactory.cls
> +    public static List<Telemetry__c> createTelemetries(Integer telemetriesNumber){
parameter name

2021-06-16 12:14 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/CarToShowroomHandler.cls
> +    public static void sendEmailAboutNewOffers(List<Car_To_Showroom__c> newOffers) {
inNewOffers

2021-06-18 06:43 UTC, AdrianDlu requested changes

2021-06-18 06:43 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/RenovationTeamCaseCreator.cls
> +        if(!Test.isRunningTest()){
Czemu wszystko jest wylaczone z testow? mysle ze tylko linia 26 powina byc w tym ifie

2021-06-18 06:43 UTC, AdrianDlu commented on InnovativeCars/force-app/main/default/classes/TestFactory.cls
> +    public static List<Telemetry__c> createTelemetries(Integer telemetriesNumber){
#Ignored?

2021-06-18 09:43 UTC, sylwiachr approved these changes

2021-06-18 09:43 UTC, merged